export const REQUEST = 'MENU_REQUEST';
export const SENDING_REQUEST = 'MENU_SENDING_REQUEST';
export const REQUEST_SUCCESS = 'MENU_REQUEST_SUCCESS';
export const REQUEST_ERROR = 'MENU_REQUEST_ERROR';

