export const REQUEST = 'CLIENTS_REQUEST';
export const SENDING_REQUEST = 'CLIENTS_SENDING_REQUEST';
export const REQUEST_SUCCESS = 'CLIENTS_REQUEST_SUCCESS';
export const REQUEST_ERROR = 'CLIENTS_REQUEST_ERROR';
