export const REQUEST = 'TABLE_REQUEST';
export const SENDING_REQUEST = 'TABLE_SENDING_REQUEST';
export const REQUEST_SUCCESS = 'TABLE_REQUEST_SUCCESS';
export const REQUEST_ERROR = 'TABLE_REQUEST_ERROR';
